data_dir = '~/.hypertask'

score_calculator = [
	"0",

	# due date calculation
		"due : now $ -", #get due delta in seconds
		"604800 @ / 2 ^ 10 *", #exponential, based on due date: 10 if due RIGHT NOW, doubles with every week overdue
		"0 @ & ?", #set to 0 if it's inf or NaN
		"+", #add to score

    # +atHome vs +atWork
		"hour $ 8 <", "hour $ 17 >", "*", #is it within work hours
		"day_of_week $ 6 = 1 -", "day_of_week $ 7 = 1 -", "*", #is it a weekday
		"* &", #I am at work
		"atHome @ atWork @ ? # 5 *", #give the active tag +5
		"@ atWork @ atHome @ ? # -7 *", #give the inactive tag -7
		"+ +", #add bonuses

	"0 updated_at : now $ - 3.1415e+7 @ / due : 0 = ? +", #if there's no due date, add a tiny score based on updated_At

	"health # 3 * +", #add a boost for +health
	"money # 5 * +", #add a boost for +money

	"& 2 * timely # due : now $ > * ?", #if the task is +timely and overdue then double the score
	"& 2 * urgent # ?", #if the task is +urgent then double the score

	"done : 0 = *", #if the task is done then multiply by 0
	"now $ wait : - 0 > *", #hide if their wait: is later than now
	"now $ snooze : - 0 > *", #hide if their snooze: is later than now

	"& 0 @ 0.01 > ?", #if the score's lower than 0.01, make it 0
]

[render]
score_precision = 2
columns = [ "id", "score", "description", "tags", "due", "recur", ]

[hooks]
on_edit='git --git-dir=$HOME/cortex/ --work-tree=$HOME add $HYPERTASK_DIR && git --git-dir=$HOME/cortex/ --work-tree=$HOME commit -am "hypertask"'
after='git --git-dir=$HOME/cortex/ --work-tree=$HOME push server'
