task_state_dir = '~/.hypertaskSync'

filter_calculator = [
	"1 1 1 1",
	# +atHome vs +atWork
		"hour $ 8.5 <", "hour $ 17.5 >", "*", #is it within work hours
		"day_of_week $ 6 = 1 -", "day_of_week $ 7 = 1 -", "*", #is it a weekday
		"*", #I am at work
		"atWork @ atHome @ ? # 1 - *", #hide anything tagged with the wrong tag
]

score_calculator = [
	"0",

	# due date calculation
		"due : now $ -", #get due delta in seconds
		"604800 @ / 2 ^ 10 *", #exponential, based on due date: 10 if due RIGHT NOW, doubles with every week overdue
		"0 @ & ?", #set to 0 if it's inf or NaN
		"+", #add to score

	"0 updated_at : now $ - 3.1415e+7 @ / due : 0 = ? +", #if there's no due date, add a tiny score based on updated_At

	"health # 3 * +", #add a boost for +health
	"money # 5 * +", #add a boost for +money

	"notioned # due : now $ < * 1 - *", #hide +notioned tasks until they're due

	"100 fuck # * +", #if the task is +fuck then add 100 to the score
	"1 2 0.5 due : now $ < ? timely # ? *", #if the task is +timely then double the score for overdue tasks, and half it for underdue tasks
	"1 2 1 due : now $ < ? moving # ? *", #if the task is +moving then double the score for overdue tasks
	"& 2 * urgent # ?", #if the task is +urgent then double the score

	"done : 0 = *", #if the task is done then multiply by 0
	"now $ wait : - 0 > *", #hide if their wait: is later than now
	"now $ snooze : - 0 > *", #hide if their snooze: is later than now

]

[render]
score_precision = 2
columns = [ "Id", "Score", "Description", "Tags", "Due", "Recur", ]

[hooks]
after='hypertask-sync-daemon ;'
