data_dir = '~/.hypertask'

[client]
post_run_hook='git --git-dir=$HOME/cortex/ --work-tree=$HOME add $HYPERTASK_DIR && git --git-dir=$HOME/cortex/ --work-tree=$HOME commit -am "hypertask"'

[server]
port=4523
